### ISSUE TITLE
labeled_pc_map_node: symbol lookup error

### ISSUE THREAD

**Issue by songanz** [UMich-BipedLab/SegmentationMapping#3]
For runing the `cassie_lidar_py.launch` file, I got the error:
```
labeled_pc_map_node: symbol lookup error: labeled_pc_map_node: undefined symbol: octomap::SemanticOcTreeNode::readData(std::basic_istream<char, std::char_traits<char> >&)
```
Can you help me with this error? I have successfully built the SegementationMapping package with octomap.

**Comment by zeroAska** [comment]
Thanks for asking, and sorry for the late reply. When you are building this repo via catkin_make, have you added "-DOCTOMAP_DIR=${you_octomap_source_directory}/lib/cmake/octomap/ "? This error means that you did not link the right path for semantic octomap.

**Comment by zhangzhen886** [comment]
@zeroAska 
I had the same problem with the error message: 

```
/home/zhenz/workspaces/minicheetah-perception/catkin_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: symbol lookup error: /home/zhenz/workspaces/minicheetah-perception/catkin_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: undefined symbol: _ZN7octomap18SemanticOcTreeNode8readDataERSi
```

And I tested the "semantic_octomap" lib [https://github.com/UMich-BipedLab/octomap](url),

![image](https://user-images.githubusercontent.com/20805398/127312798-4e56f0cf-37b7-46a7-ba94-2b0b9e6b6de0.png)

I think it is a bug in the "semantic_octomap" library, is there a solution for it?

**Comment by ArghyaChatterjee** [comment]
@zhangzhen886 , I am having exactly the same problem as yours. Have you found any solution to this problem yet ??
```
/home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: symbol lookup error: /home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: undefined symbol: _ZN7octomap18SemanticOcTreeNode8readDataERSi
================================================================================REQUIRED process [labeled_pc_map_node-3] has died!
process has died [pid 30756, exit code 127, cmd /home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node /labeled_pc_map_node/cost_map:=/labeled_pc_map_node/cost_map2 /labeled_pc_map_node/occupancy_grid:=/labeled_pc_map_node/occupancy_grid2 ~cloud_in:=/labeled_pointcloud ~cloud_out:=/labeled_pointcloud_local_pc2 __name:=labeled_pc_map_node __log:=/home/arghya/.ros/log/eb3fdf4a-f2f7-11eb-a8a4-4485007e1d87/labeled_pc_map_node-3.log].
log file: /home/arghya/.ros/log/eb3fdf4a-f2f7-11eb-a8a4-4485007e1d87/labeled_pc_map_node-3*.log
Initiating shutdown!
================================================================================
```

**Comment by ArghyaChatterjee** [comment]
Hi @zeroAska , can you look into this matter ? I can build the octomap library from this repo: https://github.com/UMich-BipedLab/octomap. 

Then I built this repo using `catkin_make install -DCMAKE_BUILD_TYPE=Release -Doctomap_DIR=/home/arghya/octomap/lib/cmake/octomap/ --pkg SegmentationMapping` and the nodes are perfectly built. But when I tried to launch the cassie_stereo_py.launch command using `roslaunch SegmentationMapping cassie_stereo_py.launch`,  the result is this:
```
/home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: symbol lookup error: /home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node: undefined symbol: _ZN7octomap18SemanticOcTreeNode8readDataERSi
================================================================================REQUIRED process [labeled_pc_map_node-3] has died!
process has died [pid 30756, exit code 127, cmd /home/arghya/segmap_ws/devel/lib/SegmentationMapping/labeled_pc_map_node /labeled_pc_map_node/cost_map:=/labeled_pc_map_node/cost_map2 /labeled_pc_map_node/occupancy_grid:=/labeled_pc_map_node/occupancy_grid2 ~cloud_in:=/labeled_pointcloud ~cloud_out:=/labeled_pointcloud_local_pc2 __name:=labeled_pc_map_node __log:=/home/arghya/.ros/log/eb3fdf4a-f2f7-11eb-a8a4-4485007e1d87/labeled_pc_map_node-3.log].
log file: /home/arghya/.ros/log/eb3fdf4a-f2f7-11eb-a8a4-4485007e1d87/labeled_pc_map_node-3*.log
Initiating shutdown!
================================================================================
```
I would request you to give it a try. During your trial, please give a fresh clone of everything like the octomap library and this repo and then try to build it. It may take 5-10 minutes of your time but the problem will be debugged.

**Comment by songanz** [comment]
Hi @ArghyaChatterjee,

I have solved my problem by uninstalling the default octomap ros library. When I install the rtabmap library for other projects, it automatically installed the default octomap. Even if I build the SegmentationMapping package with their octomap library, during runtime, it still calls the default one. That's why my problem was happening. Hope you find it useful.

**Comment by ArghyaChatterjee** [comment]
Thanks for responding @songanz . That's exactly the issue. When I built it with -Doctomap_DIR on, I get no issues and it's properly built but during runtime, it's trying to link to the original octomap library instead of the one manually built and installed. This problem should be solved by changing something in CMakelist.txt file (target link libraries) I guess. Removing the whole octomap binaries will affect a lot of other packages because most of the ros-packages require octomap library (and the version of octomap used in this repo is around 2 years old, I can't even use it for other purposes). The amount of packages will be removed from my pc:
```
arghya@arghya-Erazer-X7849-MD60379:~$ sudo apt-get remove ros-melodic-octomap
The following packages will be REMOVED:
  ros-melodic-chomp-motion-planner ros-melodic-geometric-shapes ros-melodic-moveit ros-melodic-moveit-commander ros-melodic-moveit-core
  ros-melodic-moveit-fake-controller-manager ros-melodic-moveit-kinematics ros-melodic-moveit-planners ros-melodic-moveit-planners-chomp
  ros-melodic-moveit-planners-ompl ros-melodic-moveit-plugins ros-melodic-moveit-ros ros-melodic-moveit-ros-benchmarks
  ros-melodic-moveit-ros-control-interface ros-melodic-moveit-ros-manipulation ros-melodic-moveit-ros-move-group
  ros-melodic-moveit-ros-occupancy-map-monitor ros-melodic-moveit-ros-perception ros-melodic-moveit-ros-planning ros-melodic-moveit-ros-planning-interface
  ros-melodic-moveit-ros-robot-interaction ros-melodic-moveit-ros-visualization ros-melodic-moveit-ros-warehouse ros-melodic-moveit-setup-assistant
  ros-melodic-moveit-simple-controller-manager ros-melodic-moveit-visual-tools ros-melodic-octomap ros-melodic-octomap-dbgsym ros-melodic-octomap-mapping
  ros-melodic-octomap-ros ros-melodic-octomap-ros-dbgsym ros-melodic-octomap-rviz-plugins ros-melodic-octomap-rviz-plugins-dbgsym
  ros-melodic-octomap-server ros-melodic-octomap-server-dbgsym ros-melodic-rtabmap ros-melodic-rtabmap-ros
0 upgraded, 0 newly installed, 37 to remove and 0 not upgraded.
After this operation, 103 MB disk space will be freed.
Do you want to continue? [Y/n] 
```
I can see this SegmentationMapping package is also dependent on octomap-ros. If I remove the octomap library, octomap_ros binaries will also be removed. In that case, should I manually:
i. Clone it from here: https://github.com/OctoMap/octomap_ros, 
ii. Build it (cd octomap_ros, mkdir build, cd build, cmake .., make) and 
iii. Build SegmentationMapping package using this line: 
```
catkin_make install -DCMAKE_BUILD_TYPE=Release -Doctomap_DIR=/home/arghya/octomap/lib/cmake/octomap/ -Doctomap_ros_DIR=/home/arghya/octomap_ros/lib/cmake/octomap_ros/ --pkg SegmentationMapping
```
@songanz , Can you verify these steps ( I mean this is the way to go ??) ? Thanks in advance. In the mean time, @zhangzhen886 , can you look into this matter why during building it's able to link the libraries but during runtime, it's using system binaries and is there any fix to the problem or not??

**Comment by zeroAska** [comment]
Thanks for the discussion. Yes when we built the library we also place the octomap_ros code in the same catkin_ws of the SegmentationMapping as @ArghyaChatterjee has figured out.
